export type ProfileOnboardingShape = {
  full_name?: string | null
  username?: string | null
  ciudad?: string | null
  instrumentos?: string[] | null
}

export function isAutogeneratedUsername(username?: string | null): boolean {
  const value = username?.trim() ?? ''
  if (!value) return true
  return /_[a-f0-9]{8,}$/i.test(value)
}

export function isProfileIncomplete(profile?: ProfileOnboardingShape | null): boolean {
  if (!profile) return true
  const fullName = profile.full_name?.trim() ?? ''
  const city = profile.ciudad?.trim() ?? ''
  const instruments = Array.isArray(profile.instrumentos) ? profile.instrumentos.filter(Boolean) : []
  if (!fullName) return true
  if (!city) return true
  if (instruments.length === 0) return true
  if (isAutogeneratedUsername(profile.username)) return true
  return false
}
