import { NextResponse, type NextRequest } from 'next/server'

import { isFirstOAuthSignIn } from '@/src/lib/auth/is-first-oauth-signin'
import { createSupabaseRouteHandlerClient } from '@/src/lib/supabase/route-handler'

/**
 * OAuth PKCE: el code verifier viaja en cookies enviadas por el navegador.
 * El intercambio en servidor + Set-Cookie en la respuesta de redirect evita
 * "PKCE code verifier not found" (localStorage vs cookies / SSR).
 *
 * Usuarios nuevos (primer login OAuth) → /bienvenida
 */
export async function GET(request: NextRequest) {
  const url = request.nextUrl
  const code = url.searchParams.get('code')
  const nextParam = url.searchParams.get('next') ?? '/'
  const next = nextParam.startsWith('/') ? nextParam : `/${nextParam}`

  const oauthError = url.searchParams.get('error')
  const oauthDesc = url.searchParams.get('error_description')

  if (oauthError) {
    const msg = oauthDesc || oauthError
    return NextResponse.redirect(new URL(`/login?error=${encodeURIComponent(msg)}`, url.origin))
  }

  if (!code) {
    return NextResponse.redirect(
      new URL(
        `/login?error=${encodeURIComponent('Sesión incompleta. Vuelve a intentar con Google.')}`,
        url.origin
      )
    )
  }

  const successRedirect = new URL(next, url.origin)
  let response = NextResponse.redirect(successRedirect)

  const supabase = createSupabaseRouteHandlerClient(request, response)
  const { data, error } = await supabase.auth.exchangeCodeForSession(code)

  if (error) {
    console.error('[auth/callback]', error.message)
    return NextResponse.redirect(
      new URL(`/login?error=${encodeURIComponent(error.message)}`, url.origin)
    )
  }

  let redirectPath = next
  if (data.user) {
    const meta = data.user.user_metadata as Record<string, string | undefined> | undefined
    const email = data.user.email ?? null
    const fullName =
      meta?.full_name ||
      meta?.name ||
      meta?.given_name ||
      (email ? email.split('@')[0] : 'Usuario')
    const avatarUrl = meta?.avatar_url || meta?.picture || null
    const usernameBase = (email?.split('@')[0] || 'user')
      .toLowerCase()
      .replace(/[^a-z0-9_]/g, '')
      .slice(0, 20)
    const autogeneratedUsername = `${usernameBase || 'user'}_${data.user.id.replace(/-/g, '').slice(0, 10)}`.slice(0, 40)
    const { data: existingProfile } = await supabase
      .from('profiles')
      .select('username')
      .eq('id', data.user.id)
      .maybeSingle()
    const username = existingProfile?.username || autogeneratedUsername
    await supabase.from('profiles').upsert(
      {
        id: data.user.id,
        email,
        full_name: fullName,
        avatar_url: avatarUrl,
        username,
        updated_at: new Date().toISOString(),
      },
      { onConflict: 'id' }
    )
  }

  if (data.user && isFirstOAuthSignIn(data.user)) {
    redirectPath = '/bienvenida'
  }
  response.headers.set('Location', new URL(redirectPath, url.origin).toString())

  return response
}
